name: bsmlcheck
version: 0.1.0.0
synopsis: A model checker for BSML.
description: See report.pdf
maintainer: Tiziano Coroneo <tiziano.coroneo@student.uva.nl>
category: Logic

ghc-options: -Wall

dependencies:
  - QuickCheck
  - base
  - containers
  - directory
  - lens
  - mtl
  - parsec
  - random
  - template-haskell
  - graphviz

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - bsmlcheck

tests:
  simpletests:
    main: simpletests.lhs
    source-dirs: test
    dependencies:
      - bsmlcheck
      - QuickCheck
      - hspec
